import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";
import { WavyBackground } from "@/components/ui/gradient-background";
import PortfolioFooter from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <WavyBackground
            backgroundFill="rgb(2, 6, 0)"
            colors={["#38bdf8", "#818cf8", "#c084fc", "#e879f9", "#22d3ee"]}
            waveOpacity={0.3}
            blur={15}
            speed="fast"
          >
            <main className="relative">{children}</main>
            <PortfolioFooter />
          </WavyBackground>
        </body>
      </ReactLenis>
    </html>
  );
}
